config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :users, only: [:create, :show]
  get '/signup', to: 'users#new'
  resources :sessions, only: [:create]
  get '/login', to: 'sessions#new' 
  get '/logout', to: 'sessions#destroy'
  resources :events, only: [:new,:create,:show, :index]

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/event.rb
class Event < ApplicationRecord
  belongs_to :organizer, class_name: 'User'
  has_many :event_attendances
  has_many :attendees, through: 'event_attendances', source: 'user'
  scope :past, -> { where("date < ?", Date.today) }
  scope :upcoming, -> { where("date >= ?", Date.today) }
end

app/models/event_attendance.rb
class EventAttendance < ApplicationRecord
  belongs_to :user
  belongs_to :event
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true
  validates :email, presence: true
  
  has_many :organized_events, class_name: 'Event', foreign_key: 'organizer_id'
  has_many :event_attendances
  has_many :attended_events, through: 'event_attendances', source: 'event'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  def new;  end
  
  def show
    @event = Event.find(params[:id])
  end

  def create
    @event = current_user.organized_events.build(event_params)
    if @event.save
      redirect_to @event
    else
      render 'new'
    end
  end

  def index
    @all_events = Event.all
  end

  def event_params
    params.require(:event).permit(:name, :place, :date, :description)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new;  end
  
  def create
    if @user = User.find_by(email: params[:email])
      login @user
      redirect_to @user
    else
      render 'new'
    end
  end

  def destroy
    if logged_in?
      logout
    end
    redirect_to login_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new;  end
  
  def show
    @user = User.find(params[:id])
  end
  
  def create
    @user = User.new (user_params)
    if @user.save
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def user_params
    params.require(:user).permit(:name, :email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def login(user)
    session[:current_user_id] = user.id
  end
  
  def current_user
    return nil unless session[:current_user_id]
    
    User.find(session[:current_user_id])
  end

  def logged_in?
    !current_user.nil?
  end

  def logout
    session[:current_user_id] = nil 
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/events/index.html.erb
<h1>Events:</h1>

<section>
  <h3>All Events:</h3>
  <%= render partial: 'shared/events', locals: { section_title: 'Upcoming:', events: @all_events.upcoming } %>
  <%= render partial: 'shared/events', locals: { section_title: 'Past:', events: @all_events.past } %>
</section>

app/views/events/new.html.erb
<h1>Enter Event Information:</h1>
<%= form_with model: Event.new do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :date %>
  <%= f.date_field :date %>
  <%= f.label :place %>
  <%= f.text_field :place %>
  <%= f.label :description %>
  <%= f.text_area :description %>
  <%= f.submit "Create Event" %>
<% end %>

app/views/events/show.html.erb
<h1>Event Information:</h1>

<section>
  Event: <%= @event.name  %><br>
  Place: <%= @event.place %><br>
  Date: <%= @event.date %><br>
  Organized by: <%= @event.organizer.name %>
</section>
<section>
  <h3>Attendees:</h3>
  <ul>
    <% @event.attendees.each do |a| %>
      <li><%= a.name %></li>
    <% end %>
  </ul>

</section>

app/views/layouts/_bootstrap_head.html.erb
<!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

app/views/layouts/_head.html.erb
  <head>
    <title>PrivateEvents</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= render 'layouts/bootstrap_head' %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

app/views/layouts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <% if logged_in? %>
    Logged in as: <%= current_user.name %>
    <%= link_to 'Profile', current_user, class: 'nav-link' %>
    <%= link_to 'New Event', new_event_path, class: 'nav-link' %>
    <%= link_to 'All Events', events_path, class: 'nav-link' %>
    <%= link_to 'Log Out', logout_path, class: 'nav-link' %>
  <% else %>
    <%= link_to 'Sign Up', signup_path, class: 'nav-link' %>
    <%= link_to 'Log in', login_path, class: 'nav-link' %>
  <% end %>
  </nav>
</header>

app/views/layouts/_js_for_bootstrap.html.erb
<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

  <%= render 'layouts/head' %>

  <body>
    <%= render 'layouts/header' %>
    <%= yield %>
    <%= render 'layouts/js_for_bootstrap' %>
  </body>
</html>

app/views/shared/_events.html.erb
<div>
  <h3><%= section_title %></h3>
  <table>
    <tr>
      <th>Name</th><th>Place</th><th>Date</th>
    </tr>
    <% events.each do |e| %>
      <tr>
        <td><%= link_to e.name, e %></td>
        <td><%= e.place %></td>
        <td><%= e.date %></td>
      </tr>
    <% end %>
  </table>
</div>

app/views/users/new.html.erb
<h1>Please sign up:</h1>
<%= form_with model: User.new do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :email %>
  <%= f.text_field:email %>
  <%= f.submit "Create User" %>
<% end %>

app/views/users/show.html.erb
<h1>User Information:</h1>

<section>
  Name: <%= @user.name  %>
  Email: <%= @user.email %>
</section>
<section>
  <h2>Organized Events:</h2>
  <%= render partial: 'shared/events', locals: { section_title: 'Past:', 
                                                events: @user.organized_events.past } %>
  <%= render partial: 'shared/events', locals: { section_title: 'Upcoming:', 
                                                events: @user.organized_events.upcoming } %>
</section>
<section>
  <h2>Attending Events:</h2>
  <%= render partial: 'shared/events', locals: { section_title: 'Past:', 
                                                events: @user.attended_events.past } %>
  <%= render partial: 'shared/events', locals: { section_title: 'Upcoming:', 
                                                events: @user.attended_events.upcoming } %>
</section>